---
- name: Testing andrewrothstein.sonarscannercli
  hosts: all
  tasks:
    - name: Testing (javaless)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      vars:
        sonarscannercli_javaless: true
    - name: Testing (default)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
