---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for install in {{ sonarscannercli_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ sonarscannercli_install_dir }}'
  changed_when: false
  register: sonarscannercli_binary
- name: Downloading and installing the sonarscanner-cli
  when: not sonarscannercli_binary.stat.exists
  block:
    - name: Downloading {{ sonarscannercli_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ sonarscannercli_url }}'
        dest: '{{ sonarscannercli_tmp_zip }}'
        mode: '644'
        checksum: '{{ sonarscannercli_checksum }}'
    - name: Unarchiving {{ sonarscannercli_tmp_zip }} into {{ sonarscannercli_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ sonarscannercli_tmp_zip }}'
        dest: '{{ sonarscannercli_parent_install_dir }}'
        creates: '{{ sonarscannercli_install_dir }}'
  always:
    - name: Rm {{ sonarscannercli_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ sonarscannercli_tmp_zip }}'
        state: absent
- name: Linking {{ sonarscannercli_link_dir }} to executables in {{ sonarscannercli_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ sonarscannercli_install_dir }}'
    dest: '{{ sonarscannercli_link_dir }}'
    state: link
- name: Add to default shell path
  become: true
  become_user: root
  with_items:
    - f: sonarscannercli.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
- name: Warming up sonarscanner-cli cache
  when: sonarscannercli_cache_warmup
  environment:
    JAVA_HOME: '{{ sonarscannercli_java_home }}'
  command: '{{ sonarscannercli_install_dir }}/bin/sonar-scanner -Dsonar.host.url={{ sonarscannercli_host_url }} --debug'
  changed_when: false
  ignore_errors: true
