---
- include_role:
    name: andrewrothstein.unarchivedeps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for install in {{ sonarscannercli_install_dir }}
  become: true
  stat:
    path: '{{ sonarscannercli_install_dir }}'
  changed_when: false
  register: sonarscannercli_binary
- when: not sonarscannercli_binary.stat.exists
  block:
    - name: downloading {{ sonarscannercli_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ sonarscannercli_url }}'
        dest: '{{ sonarscannercli_tmp_zip }}'
        mode: 0644
        checksum: '{{ sonarscannercli_checksum }}'
    - name: unarchiving {{ sonarscannercli_tmp_zip }} into {{ sonarscannercli_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ sonarscannercli_tmp_zip }}'
        dest: '{{ sonarscannercli_parent_install_dir }}'
        creates: '{{ sonarscannercli_install_dir }}'
  always:
    - name: rm {{ sonarscannercli_tmp_zip }}
      become: true
      become_user: root
      file:
        path: '{{ sonarscannercli_tmp_zip }}'
        state: absent
- name: linking {{ sonarscannercli_link_dir }} to executables in {{ sonarscannercli_install_dir }}
  become: true
  become_user: root
  file:
    src: '{{ sonarscannercli_install_dir }}'
    dest: '{{ sonarscannercli_link_dir }}'
    state: link
- name: add to default shell path
  become: true
  become_user: root
  with_items:
    - f: sonarscannercli.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
- name: warmup sonarscanner cli cache
  when: sonarscannercli_cache_warmup
  environment:
    JAVA_HOME: '{{ sonarscannercli_java_home }}'
  command: '{{ sonarscannercli_install_dir }}/bin/sonar-scanner -Dsonar.host.url={{ sonarscannercli_host_url }} --debug'
  ignore_errors: true
